### PR TITLE
EPL Statstics

### PR DESCRIPTION
**Pull request by nati-m-afw**

### CODE REVIEW

**Review by BarokDG — COMMENTED** [review]
Looks good to me.

**Comment by nati-m-afw** [comment]
I think we need to setup a remote mongo server for github to run the tests

**Comment by BarokDG** [comment]
Yeah, that would be great. Once we've reviewed everything we'll set it up then merge to main.

**Comment by nati-m-afw** [comment]
I believe there is a github action for it. Will add it in Express CI when i get the chance.

**Comment by nati-m-afw** [comment]
> Yeah, that would be great. Once we've reviewed everything we'll set it up then merge to main.

Done✔

**Pull request merged**
